###
# This is the place to override the rails cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "rails/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Rails version used:
#
#normal[:rails][:version] = "2.3.18"

#node[:deploy].each do |application, deploy|
#  node.default[:deploy][application][:static_assets][:compilation_env] = 'staging'
#  node.default[:deploy][application][:environments] = ['development', 'production'] +
#    [node.default[:deploy][application][:static_assets][:compilation_env]]
#end